version: "3"
services:
  db:
    image: docker.io/centos/postgresql-96-centos7
    environment:
      - POSTGRESQL_USER=dci
      - POSTGRESQL_PASSWORD=dci
      - POSTGRESQL_DATABASE=dci
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-db:/opt/app-root/src:Z
    ports:
      - "5432:5432"
    healthcheck:
      test: source /opt/rh/rh-postgresql96/enable && pg_isready -d dci -U dci -h db
      interval: 15s
      timeout: 5s
      retries: 5
  api:
    build: ${DCI_GIT_REPO_DIR}/dci-control-server
    depends_on:
      db:
        condition: service_healthy
    env_file: ${DCI_GIT_REPO_DIR}/.env
    ports:
      - "5000:5000"
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-control-server:/opt/dci-control-server:Z
    restart: always
    healthcheck:
      test: curl -sf http://api:5000/api/v1
      interval: 15s
      timeout: 5s
      retries: 5
  ui:
    build: ${DCI_GIT_REPO_DIR}/dci-ui
    depends_on:
      api:
        condition: service_healthy
    environment:
      - REACT_APP_BACKEND_HOST=http://localhost:5000
      - REACT_APP_SSO_URL=${SSO_URL}
      - REACT_APP_SSO_REALM=${SSO_REALM}
      - REACT_APP_SSO_CLIENT_ID=${SSO_CLIENT_ID}
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true  
    ports:
      - "8000:8000"
    healthcheck:
      test: curl -sf http://ui:8000
      interval: 15s
      timeout: 5s
      retries: 5
    volumes:
      - ${DCI_GIT_REPO_DIR}/dci-ui:/opt/app-root/src:Z
      - /opt/app-root/src/node_modules
  client:
    build: ${DCI_GIT_REPO_DIR}/python-dciclient
    depends_on:
      api:
        condition: service_started
    env_file: ${DCI_GIT_REPO_DIR}/.env
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ${DCI_GIT_REPO_DIR}/python-dciclient:/opt/python-dciclient:Z
      - ${DCI_GIT_REPO_DIR}/dci-control-server:/opt/dci-control-server:Z
