# --- 1. SSL-Bump / MITM Configuration ---
# Listen on 3128. cert/key are generated in entrypoint.sh
http_port 3128 tcpkeepalive=60,30,3 ssl-bump generate-host-certificates=on dynamic_cert_mem_cache_size=4MB cert=/etc/squid/cert.crt key=/etc/squid/cert.key

# Initialize the SSL Certificate DB helper
sslcrtd_program /usr/lib64/squid/security_file_certgen -s /var/lib/squid/ssl_db -M 4MB

# Peek at the SNI (step 1) then Bump (decrypt) everything (step 2)
acl step1 at_step SslBump1
ssl_bump peek step1
ssl_bump bump all

# --- Authenticators ---
auth_param basic program /opt/bin/acl-helper.py
auth_param basic children 10
auth_param basic realm Registry Proxy

# --- External ACL Helper ---
external_acl_type registry_selector %ul %credentials %DST /opt/bin/acl-helper.py

# --- ACL Definitions ---
acl authenticated_user proxy_auth REQUIRED
acl has_bearer_token req_header Authorization ^Bearer\s
acl is_quay_domain dstdomain quay.io
acl is_openshift_ci_domain dstdomain registry.ci.openshift.org
acl is_s3_domain dstdomain s3.amazonaws.com
acl valid_registry_tags external registry_selector QUAY_AUTH DOCKER_AUTH OPENSHIFT_CI_AUTH
# acl auth_openshift_ci external registry_selector IS_OPENSHIFT_CI
# acl auth_quay external registry_selector IS_QUAY

# --- Header Injection & Inclusion ---
request_header_access Authorization allow is_s3_domain
request_header_access Authorization allow has_bearer_token
request_header_access Authorization allow valid_registry_tags
# request_header_access Authorization allow auth_quay
# request_header_access Authorization allow auth_openshift_ci
request_header_access Authorization deny all
request_header_access Proxy-Authorization deny all

# --- Final Access Rules ---
# http_access allow auth_quay
# http_access allow auth_openshift_ci
http_access allow valid_registry_tags
http_access deny all

# include the secret request_header_add
include /etc/squid/secrets.conf

# --- Logging ---
# %ts.%03tu: Timestamp
# %>a: Client IP
# %Ss/%03Hs: Status Code
# %rm %ru: Request Method and URL
logformat auth_debug %ts.%03tu %>a %Ss/%03Hs %rm %ru
access_log stdio:/dev/stdout auth_debug
cache_log /dev/stderr
